name: balance_cbs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  sqflite: ^2.3.3
  qr_code_scanner_plus: ^2.0.10+1
  image_picker: ^1.0.1
  # scan: ^1.6.0
  mime: ^2.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  dio: ^5.7.0
  mobile_scanner: ^7.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.2.3
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  geolocator: ^14.0.0
  uuid: ^4.5.1
  sunmi_printer_plus: ^2.1.2
  number_to_words_nepali: ^1.3.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_launcher_icons: ^0.14.3
  # flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    # - assets/icons/balance.png
    - assets/icons/Splash.png
    - assets/icons/group.png
    - assets/icons/
    - assets/
    - assets/logo/
    - assets/common/
    - assets/menu/
    - assets/profile/
    - assets/receipt/
    - assets/push/


# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/logo/splash1.png" # your transparent logo
#   background_color: "#23538D" 
#   adaptive_icon_background: "#23538D"
#   adaptive_icon_foreground: "assets/logo/splash1.png"

# flutter_native_splash:
#   # color: "#ffffff"
#   color: "#23538d" # Background color
#   image: assets/logo/splash1.png # Path to your splash image
#   # branding: assets/branding.png # Optional - small logo at bottom
#   android_gravity: center # Image alignment
#   ios_content_mode: scaleAspectFit
#   fullscreen: true
